'use client';
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { usePathname } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // Only show Navbar/Footer for main (public) routes
  const pathname = typeof window !== 'undefined' ? window.location.pathname : '';
  const isUserOrAdmin = pathname.startsWith('/user') || pathname.startsWith('/admin');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!isUserOrAdmin && <Navbar />}
        <Toaster />
        {children}
        {!isUserOrAdmin && <Footer />}
      </body>
    </html>
  );
}
